#!/usr/bin/env python3
# This is for testing purposes only

import random
import sys
import json

def get_object():
    poll = {"native": { "pollinterval": "2000", }, }
    print(json.dumps(poll))

def get_state():
    print(round(random.uniform(0,4500),3), end='')

def broker(v):
    switcher={
            "object" : get_object,
            "state" : get_state,
            }
    return switcher.get(v,"")()

if len(sys.argv) < 2:
    sys.exit(1)

broker(sys.argv[1])
